### ISSUE TITLE
.stream() bypasses the "Have you installed graphicsmagick or imageMagick" check.

### ISSUE THREAD

**Issue by rxaviers** [aheckmann/gm#122]
`.stream()` bypasses the "Have you installed graphicsmagick or imageMagick" check.

Differently from `.write()`, `.stream()` calls `_spawn()` with `bufferOutput = false`. The callback function gets the stdin and stderr streams, but not the `proc` so it could listen to the return code of end/close event.

This can be tested in a non-installed GM/IM machine with:

``` javascript
gm("logo:").stream("png", cb);
```

vs.

``` javascript
gm("logo:").write("/tmp/test.png", cb);
```

**Comment by ricardograca** [comment]
@jonathanong Is it hard/impossible to implement this?

Besides just having this exact same problem even though I had imagemagick installed, I can see some error reports about people getting this same unhelpful error message. If this is impossible how about implementing an automatic check for imagemagick instead of requiring the user to pass it as an option? Would that be possible to implement?
