### ISSUE TITLE
Ability to specify custom path to binaries

### ISSUE THREAD

**Issue by darsain** [aheckmann/gm#203]
I want to be able to set a custom path to gm/imagick binaries. Tried looking in docs, and later searching for something like that in code, but found only `.command()`, `.subCommand()` and `this._subCommand`, which isn't really what I want.

Something like node-imagemagick's `this.convert.path` & `this.identify.path`. Or a global `this.path` that would get prepended to every command. Or both :) I'd personally use `this.path`.

**Comment by rwky** [comment]
Done in 969b966f4e82f0b365f05611d0262cdde5be018f

**Comment by oscarjiv91** [comment]
Hello, I tried to set the path of the bin this way: 
`const gm = require('gm').subClass({imageMagick: true, appPath: '/The/Path/Of/Bin'});`

Is that the way to specify it? Because I have this error:
Could not execute GraphicsMagick/ImageMagick: /The/Path/Of/Binconvert "1.jpg" "-resize" "240x240" "+profile" "\"*\"" "1_resized.jpg" this most likely means the gm/convert binaries can't be found

And yes, I'm sure that is the path to the bin

**Comment by ir-fuel** [comment]
Is this documented somewhere?
