### ISSUE TITLE
resizeExact doesn't seem to work

### ISSUE THREAD

**Issue by corysimmons** [aheckmann/gm#433]
Copied your example from the README

```js
var fs = require('fs')
  , gm = require('gm');

gm('500x1000.jpg')
	.resizeExact(700, 700)
	.write('500x1000-resized.jpg', function(err) {
	  if (!err) console.log('done');
	});
```

But I get a console err:

```
	.resizeExact(700, 700)
	 ^
TypeError: undefined is not a function
```

Works with `resize`. Any ideas?

**Comment by corysimmons** [comment]
I suppose `resizeExact` is just an alias to `resize` with the `'!'` though. Just thought I'd give you a heads up.

**Comment by DanMMX** [comment]
Can you tell us which version are you using?

If installed from [npm](https://www.npmjs.com/package/gm) there hasn't been any push on to npm since 3 months ago from @rwky . If you need that method which was pushed on July 18 please use `npm install git://github.com/aheckmann/gm.git#master`

Let me know if this works

**Comment by corysimmons** [comment]
Ah, totally lost track of this Issue and I'm not even messing around with `gm` anymore. I forget. Sorry.

Hopefully a new version has been pushed to npm and fixed it. :)
