### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [aheckmann/gm#775]
Hi, what is the current status of this project? Is it still actively maintained or are you looking for maintainers?

**Comment by kachkaev** [comment]
@aheckmann? 🙏

**Comment by dlong500** [comment]
Considering no one even replied to this issue in the past 2.5 years and there hasn't been a commit in over 3.5 years I'd say it is abandoned.  That is unfortunate.  Hopefully @aheckmann is OK; maybe just too busy with life to continue as a maintainer.  @DanielRuf Have you found a fork being maintained or an alternative?  It's hard to figure out activity within the forks because there are so many of them.  There are definitely some updates that are needed (such as not working with Imagemagick 7+).

**Comment by DanielRuf** [comment]
@dlong500 according to https://useful-forks.github.io/?repo=aheckmann%2Fgm there is at least one fork with 97 commits that were added after the last commit here.

The fork that I mean is https://github.com/fatchan/gm

**Comment by dlong500** [comment]
@DanielRuf Thanks!  That's a useful site too.  I hadn't found that before.

**Comment by DanielRuf** [comment]
> @DanielRuf Thanks! That's a useful site too. I hadn't found that before.

I guess this (useful forks) is added as button there (https://github.com/aheckmann/gm/network/members)

<img width="393" alt="Bildschirmfoto 2021-08-05 um 20 49 17" src="https://user-images.githubusercontent.com/827205/128404867-19ad7d30-1526-4d0b-9024-84ca76033b80.png">

by this extension in my browser:

https://github.com/sindresorhus/refined-github

https://github.com/sindresorhus/refined-github#repositories

> Helps you find the most active forks, via useful-forks.github.io.
